-- Add short numeric order number for UI/emails/notifications.
-- Postgres: use IDENTITY for auto-increment semantics.

ALTER TABLE "Order"
ADD COLUMN "orderNumber" INTEGER GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX "Order_orderNumber_key" ON "Order"("orderNumber");

