-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "tab1Title" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "tab2Title" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "tab3Title" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "tab4Title" TEXT;
