import type { JSONContent } from '@tiptap/core'
import type { BrandId } from '@/lib/brand/brand'

export interface ContentBlockDefault {
  brand?: BrandId
  page: string
  key: string
  label: string
  type: 'short' | 'rich'
  text?: string
  richJson?: JSONContent
  colorToken?: string
  fontVariant?: string
  /** thin | light | normal | medium | semibold | bold | extrabold */
  fontWeight?: string
}

export interface AdminContentBlockSchemaEntry {
  page: string
  key: string
  adminLabel?: string
}

const INNER_HOME_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  { page: 'home', key: 'hero.badge' },
  { page: 'home', key: 'hero.title' },
  { page: 'home', key: 'hero.title.highlight' },
  { page: 'home', key: 'hero.subtitle' },
  { page: 'home', key: 'home.new.subtitle' },
  { page: 'home', key: 'home.news.subtitle' },
  {
    page: 'home',
    key: 'home.news.showWhenEmpty',
    adminLabel: 'Новости на главной — показывать блок без постов (1 / да / on)',
  },
  { page: 'home', key: 'home.catalog.subtitle' },
  { page: 'home', key: 'home.articles.subtitle' },
  {
    page: 'home',
    key: 'home.articles.showWhenEmpty',
    adminLabel: 'Статьи на главной — показывать блок без постов (1 / да / on)',
  },
  { page: 'home', key: 'home.reviews.subtitle' },
] as const

const SPRINT_HOME_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  { page: 'home', key: 'hero.badge' },
  { page: 'home', key: 'hero.title' },
  { page: 'home', key: 'hero.subtitle' },
  {
    page: 'home',
    key: 'hero.featuredProductId',
    adminLabel: 'Hero — ID товара для карточки справа (если пусто — берём по флагу isFeaturedInNewArrivals)',
  },
  { page: 'home', key: 'newsBlock.eyebrow' },
  { page: 'home', key: 'newsBlock.title' },
  { page: 'home', key: 'home.news.subtitle' },
  {
    page: 'home',
    key: 'home.news.showWhenEmpty',
    adminLabel: 'Новости на главной — показывать блок без постов (1 / да / on)',
  },
  { page: 'home', key: 'articlesBlock.eyebrow' },
  { page: 'home', key: 'articlesBlock.title' },
  { page: 'home', key: 'home.articles.subtitle' },
  {
    page: 'home',
    key: 'home.articles.showWhenEmpty',
    adminLabel: 'Статьи на главной — показывать блок без постов (1 / да / on)',
  },
  { page: 'home', key: 'hero.cta.primary' },
  { page: 'home', key: 'hero.cta.secondary' },
  { page: 'home', key: 'hero.featured' },
  { page: 'home', key: 'about.title', adminLabel: 'Главная — блок «О нас» заголовок' },
  { page: 'home', key: 'hits.title' },
  { page: 'home', key: 'reviews.title' },
  { page: 'home', key: 'markers.title' },
  { page: 'home', key: 'markers.item1' },
  { page: 'home', key: 'markers.item2' },
  { page: 'home', key: 'markers.item3' },
  { page: 'home', key: 'reviewsCta.title' },
  { page: 'home', key: 'reviewsCta.text' },
  { page: 'home', key: 'reviewsCta.buttonLabel' },
  { page: 'home', key: 'reviewsCta.href' },
  { page: 'home', key: 'lineup.title' },
  { page: 'home', key: 'crossBrand.title' },
  { page: 'home', key: 'crossBrand.text' },
  { page: 'home', key: 'crossBrand.cta' },
  { page: 'home', key: 'faq.title', adminLabel: 'Главная — FAQ teaser заголовок' },
  { page: 'home', key: 'faq.cta', adminLabel: 'Главная — FAQ teaser CTA' },
] as const

const ABOUT_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  { page: 'about', key: 'about.block1' },
  { page: 'about', key: 'about.block2.title' },
  { page: 'about', key: 'about.block2.text' },
  { page: 'about', key: 'about.image1.src' },
  { page: 'about', key: 'about.image1.alt' },
  { page: 'about', key: 'about.image2.src' },
  { page: 'about', key: 'about.image2.alt' },
] as const

const CATALOG_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  { page: 'catalog', key: 'categories.fontVariant' },
] as const

const INNER_FAQ_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  { page: 'faq', key: 'faq.title', adminLabel: 'Страница FAQ — заголовок' },
  { page: 'faq', key: 'faq.subtitle', adminLabel: 'Страница FAQ — подзаголовок' },
  { page: 'home', key: 'howToOrder.title', adminLabel: 'FAQ / Как заказать — заголовок' },
  { page: 'home', key: 'howToOrder.step1.title', adminLabel: 'FAQ / Как заказать — шаг 1 заголовок' },
  { page: 'home', key: 'howToOrder.step1.text', adminLabel: 'FAQ / Как заказать — шаг 1 текст' },
  { page: 'home', key: 'howToOrder.step1.href', adminLabel: 'FAQ / Как заказать — шаг 1 ссылка' },
  { page: 'home', key: 'howToOrder.step1.linkLabel', adminLabel: 'FAQ / Как заказать — шаг 1 текст ссылки' },
  { page: 'home', key: 'howToOrder.step2.title', adminLabel: 'FAQ / Как заказать — шаг 2 заголовок' },
  { page: 'home', key: 'howToOrder.step2.text', adminLabel: 'FAQ / Как заказать — шаг 2 текст' },
  { page: 'home', key: 'howToOrder.step2.href', adminLabel: 'FAQ / Как заказать — шаг 2 ссылка' },
  { page: 'home', key: 'howToOrder.step2.linkLabel', adminLabel: 'FAQ / Как заказать — шаг 2 текст ссылки' },
  { page: 'home', key: 'howToOrder.step3.title', adminLabel: 'FAQ / Как заказать — шаг 3 заголовок' },
  { page: 'home', key: 'howToOrder.step3.text', adminLabel: 'FAQ / Как заказать — шаг 3 текст' },
  { page: 'home', key: 'howToOrder.step3.href', adminLabel: 'FAQ / Как заказать — шаг 3 ссылка' },
  { page: 'home', key: 'howToOrder.step3.linkLabel', adminLabel: 'FAQ / Как заказать — шаг 3 текст ссылки' },
] as const

const SPRINT_FAQ_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  { page: 'faq', key: 'faq.title', adminLabel: 'Страница FAQ — заголовок' },
  { page: 'faq', key: 'faq.subtitle', adminLabel: 'Страница FAQ — подзаголовок' },
  { page: 'home', key: 'howToOrder.title', adminLabel: 'FAQ / Как заказать — заголовок' },
  { page: 'home', key: 'howToOrder.step1.title', adminLabel: 'FAQ / Как заказать — шаг 1 заголовок' },
  { page: 'home', key: 'howToOrder.step1.text', adminLabel: 'FAQ / Как заказать — шаг 1 текст' },
  { page: 'home', key: 'howToOrder.step1.href', adminLabel: 'FAQ / Как заказать — шаг 1 ссылка' },
  { page: 'home', key: 'howToOrder.step1.linkLabel', adminLabel: 'FAQ / Как заказать — шаг 1 текст ссылки' },
  { page: 'home', key: 'howToOrder.step2.title', adminLabel: 'FAQ / Как заказать — шаг 2 заголовок' },
  { page: 'home', key: 'howToOrder.step2.text', adminLabel: 'FAQ / Как заказать — шаг 2 текст' },
  { page: 'home', key: 'howToOrder.step2.href', adminLabel: 'FAQ / Как заказать — шаг 2 ссылка' },
  { page: 'home', key: 'howToOrder.step2.linkLabel', adminLabel: 'FAQ / Как заказать — шаг 2 текст ссылки' },
  { page: 'home', key: 'howToOrder.step3.title', adminLabel: 'FAQ / Как заказать — шаг 3 заголовок' },
  { page: 'home', key: 'howToOrder.step3.text', adminLabel: 'FAQ / Как заказать — шаг 3 текст' },
  { page: 'home', key: 'howToOrder.step3.href', adminLabel: 'FAQ / Как заказать — шаг 3 ссылка' },
  { page: 'home', key: 'howToOrder.step3.linkLabel', adminLabel: 'FAQ / Как заказать — шаг 3 текст ссылки' },
] as const

const CONTACTS_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  { page: 'contacts', key: 'contacts.title' },
  { page: 'contacts', key: 'contacts.section.contacts_title' },
  { page: 'contacts', key: 'contacts.label.phone' },
  { page: 'contacts', key: 'contacts.phone' },
  { page: 'contacts', key: 'contacts.label.email' },
  { page: 'contacts', key: 'contacts.email' },
  { page: 'contacts', key: 'contacts.section.showroom_title' },
  { page: 'contacts', key: 'contacts.address' },
  { page: 'contacts', key: 'contacts.section.schedule_title' },
  { page: 'contacts', key: 'contacts.working_weekdays' },
  { page: 'contacts', key: 'contacts.working_weekends' },
  { page: 'contacts', key: 'contacts.working_note' },
  { page: 'contacts', key: 'contacts.section.write_title' },
] as const

const CART_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  {
    page: 'cart',
    key: 'cart.paymentSuccessMessage',
    adminLabel: 'Корзина — сообщение после успешной оплаты',
  },
] as const

const COOPERATION_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  { page: 'sotrudnichestvo', key: 'cooperation.title' },
  { page: 'sotrudnichestvo', key: 'cooperation.subtitle' },
  { page: 'sotrudnichestvo', key: 'cooperation.form.title' },
  { page: 'sotrudnichestvo', key: 'cooperation.form.subtitle' },
  { page: 'sotrudnichestvo', key: 'cooperation.intro.title' },
  { page: 'sotrudnichestvo', key: 'cooperation.intro.p1' },
  { page: 'sotrudnichestvo', key: 'cooperation.intro.p2' },
  { page: 'sotrudnichestvo', key: 'cooperation.intro.p3' },
  { page: 'sotrudnichestvo', key: 'cooperation.audience.title' },
  { page: 'sotrudnichestvo', key: 'cooperation.audience.text' },
  { page: 'sotrudnichestvo', key: 'cooperation.benefits.title' },
  { page: 'sotrudnichestvo', key: 'cooperation.benefits.item1' },
  { page: 'sotrudnichestvo', key: 'cooperation.benefits.item2' },
  { page: 'sotrudnichestvo', key: 'cooperation.benefits.item3' },
  { page: 'sotrudnichestvo', key: 'cooperation.extra.title' },
  { page: 'sotrudnichestvo', key: 'cooperation.extra.item1' },
  { page: 'sotrudnichestvo', key: 'cooperation.extra.item2' },
  { page: 'sotrudnichestvo', key: 'cooperation.extra.item3' },
] as const

const CERTIFICATES_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  { page: 'certificates', key: 'certificates.title' },
  { page: 'certificates', key: 'certificates.subtitle' },
  { page: 'certificates', key: 'certificates.gallery.image1.src' },
  { page: 'certificates', key: 'certificates.gallery.image1.alt' },
  { page: 'certificates', key: 'certificates.gallery.image2.src' },
  { page: 'certificates', key: 'certificates.gallery.image2.alt' },
  { page: 'certificates', key: 'certificates.gallery.image3.src' },
  { page: 'certificates', key: 'certificates.gallery.image3.alt' },
  { page: 'certificates', key: 'certificates.gallery.image4.src' },
  { page: 'certificates', key: 'certificates.gallery.image4.alt' },
  { page: 'certificates', key: 'certificates.gallery.image5.src' },
  { page: 'certificates', key: 'certificates.gallery.image5.alt' },
  { page: 'certificates', key: 'certificates.gallery.image6.src' },
  { page: 'certificates', key: 'certificates.gallery.image6.alt' },
  { page: 'certificates', key: 'certificates.section.about.title' },
  { page: 'certificates', key: 'certificates.section.about.p1' },
  { page: 'certificates', key: 'certificates.section.about.p2' },
  { page: 'certificates', key: 'certificates.section.declarations.title' },
  { page: 'certificates', key: 'certificates.section.declarations.p1' },
  { page: 'certificates', key: 'certificates.section.declarations.note' },
  { page: 'certificates', key: 'certificates.section.productCertificates.title' },
  { page: 'certificates', key: 'certificates.section.productCertificates.p1' },
  { page: 'certificates', key: 'certificates.section.productCertificates.note' },
  { page: 'certificates', key: 'certificates.section.contacts.title' },
  { page: 'certificates', key: 'certificates.section.contacts.intro' },
  { page: 'certificates', key: 'certificates.section.contacts.email' },
  { page: 'certificates', key: 'certificates.section.contacts.contactsPageLabel' },
] as const

const FOOTER_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  { page: 'footer', key: 'footer.legal.fullName' },
  { page: 'footer', key: 'footer.legal.address' },
  { page: 'footer', key: 'footer.bank.correspondentAccount' },
  { page: 'footer', key: 'footer.bank.bic' },
  { page: 'footer', key: 'footer.bank.ogrnip' },
  { page: 'footer', key: 'footer.bank.inn' },
] as const

/** Юридические страницы: один rich-блок на страницу (пока пустой в defaults → кодовый fallback на витрине). */
const LEGAL_PAGES_ADMIN_SCHEMA: readonly AdminContentBlockSchemaEntry[] = [
  {
    page: 'legal-privacy',
    key: 'legal-privacy.body',
    adminLabel: 'Политика конфиденциальности — основной текст',
  },
  {
    page: 'legal-oferta',
    key: 'legal-oferta.body',
    adminLabel: 'Публичная оферта — основной текст',
  },
] as const

const ADMIN_CONTENT_SCHEMA: Record<
  BrandId,
  Partial<Record<string, readonly AdminContentBlockSchemaEntry[]>>
> = {
  inner: {
    home: INNER_HOME_ADMIN_SCHEMA,
    about: ABOUT_ADMIN_SCHEMA,
    catalog: CATALOG_ADMIN_SCHEMA,
    faq: INNER_FAQ_ADMIN_SCHEMA,
    contacts: CONTACTS_ADMIN_SCHEMA,
    cart: CART_ADMIN_SCHEMA,
    certificates: CERTIFICATES_ADMIN_SCHEMA,
    sotrudnichestvo: COOPERATION_ADMIN_SCHEMA,
    footer: FOOTER_ADMIN_SCHEMA,
    ...Object.fromEntries(LEGAL_PAGES_ADMIN_SCHEMA.map((e) => [e.page, [e]] as const)),
  },
  'sprint-power': {
    home: SPRINT_HOME_ADMIN_SCHEMA,
    about: ABOUT_ADMIN_SCHEMA,
    catalog: CATALOG_ADMIN_SCHEMA,
    faq: SPRINT_FAQ_ADMIN_SCHEMA,
    contacts: CONTACTS_ADMIN_SCHEMA,
    cart: CART_ADMIN_SCHEMA,
    certificates: CERTIFICATES_ADMIN_SCHEMA,
    sotrudnichestvo: COOPERATION_ADMIN_SCHEMA,
    footer: FOOTER_ADMIN_SCHEMA,
    ...Object.fromEntries(LEGAL_PAGES_ADMIN_SCHEMA.map((e) => [e.page, [e]] as const)),
  },
}

export function getAdminContentSchemaForBrandPage(
  brandId: BrandId,
  page: string
): readonly AdminContentBlockSchemaEntry[] {
  return ADMIN_CONTENT_SCHEMA[brandId][page] ?? []
}

export const CONTENT_BLOCK_DEFAULTS: ContentBlockDefault[] = [
  // Home / Hero
  {
    page: 'home',
    key: 'hero.badge',
    label: 'Hero — бейдж',
    type: 'short',
    text: 'НОВЫЙ СТАНДАРТ БИОДОБАВОК',
    colorToken: 'text-white',
  },
  {
    page: 'home',
    key: 'hero.title',
    label: 'Hero — заголовок',
    type: 'short',
    text: 'Функциональное\nпитание для\nтвоего\nбаланса.',
    colorToken: 'text-white',
    fontWeight: 'thin',
  },
  {
    page: 'home',
    key: 'hero.title.highlight',
    label: 'Hero — какое слово выделить цветом',
    type: 'short',
    text: 'твоего',
    colorToken: 'text-blue-300',
  },
  {
    page: 'home',
    key: 'hero.subtitle',
    label: 'Hero — подзаголовок',
    type: 'short',
    text: 'Мы объединили чистоту натуральных ингредиентов и высокие технологии для поддержания вашего здоровья на клеточном уровне.',
    colorToken: 'text-slate-300',
    fontWeight: 'light',
  },

  // Home sections
  {
    page: 'home',
    key: 'home.new.subtitle',
    label: 'Новинки — подпись',
    type: 'short',
    text: 'Самые актуальные разработки для вашего здоровья и энергии',
    colorToken: 'text-slate-500',
  },
  {
    page: 'home',
    key: 'home.news.subtitle',
    label: 'Новости — подпись',
    type: 'short',
    text: 'Актуальные события и обновления',
    colorToken: 'text-slate-500',
  },
  {
    page: 'home',
    key: 'home.news.showWhenEmpty',
    label: 'Новости на главной — показывать без постов',
    type: 'short',
  },
  {
    page: 'home',
    key: 'home.catalog.subtitle',
    label: 'Разделы каталога — подпись',
    type: 'short',
    text: 'Выберите категорию для быстрого поиска нужного продукта',
    colorToken: 'text-slate-500',
  },
  {
    page: 'home',
    key: 'home.articles.subtitle',
    label: 'Статьи — подпись',
    type: 'short',
    text: 'Полезные материалы о здоровье и нутриентах',
    colorToken: 'text-slate-500',
  },
  {
    page: 'home',
    key: 'home.articles.showWhenEmpty',
    label: 'Статьи на главной — показывать без постов',
    type: 'short',
  },
  {
    page: 'home',
    key: 'home.reviews.subtitle',
    label: 'Отзывы — подпись',
    type: 'short',
    text: 'Мнения наших клиентов',
    colorToken: 'text-slate-500',
  },

  // Home — блок отзывов (CTA)
  {
    page: 'home',
    key: 'home.reviews.cta.title',
    label: 'Отзывы (CTA) — заголовок',
    type: 'short',
    text: 'Нам важно ваше мнение',
    colorToken: 'text-white',
  },
  {
    page: 'home',
    key: 'home.reviews.cta.text',
    label: 'Отзывы (CTA) — текст',
    type: 'short',
    text: 'Оставьте отзыв — он появится на сайте после модерации. Ваш опыт помогает другим выбирать лучшее.',
    colorToken: 'text-slate-400',
  },

  // Home — Sprint Power блок
  {
    page: 'home',
    key: 'home.sprint.title',
    label: 'Sprint Power — заголовок',
    type: 'short',
    text: 'Больше чем спорт. Чистая энергия.',
    colorToken: 'text-slate-900',
  },
  {
    page: 'home',
    key: 'home.sprint.text',
    label: 'Sprint Power — текст',
    type: 'short',
    text: 'Sprint Power — это инновационные формулы, правильные пропорции и высококачественное сырье в биодоступной форме. Добавки, которые сделают ваши тренировки эффективнее, а победы — ярче.',
    colorToken: 'text-slate-600',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'newsBlock.eyebrow',
    label: 'Новости — eyebrow',
    type: 'short',
    text: 'Контент Sprint',
    colorToken: 'text-blue-400',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'newsBlock.title',
    label: 'Новости — заголовок',
    type: 'short',
    text: 'Новости',
    colorToken: 'text-white',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'home.news.subtitle',
    label: 'Новости — подпись',
    type: 'short',
    text: 'Запуски продуктов, обновления линейки и события бренда Sprint Power.',
    colorToken: 'text-slate-300',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'articlesBlock.eyebrow',
    label: 'Статьи — eyebrow',
    type: 'short',
    text: 'Материалы и гайды',
    colorToken: 'text-action-blue',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'articlesBlock.title',
    label: 'Статьи — заголовок',
    type: 'short',
    text: 'Статьи',
    colorToken: 'text-slate-900',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'home.articles.subtitle',
    label: 'Статьи — подпись',
    type: 'short',
    text: 'Разборы составов, рекомендации по приёму и материалы про тренировки и восстановление.',
    colorToken: 'text-slate-600',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'hero.badge',
    label: 'Hero — бейдж',
    type: 'short',
    text: 'SPRINT POWER',
    colorToken: 'text-white',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'hero.title',
    label: 'Hero — заголовок',
    type: 'short',
    text: 'Почувствуй разницу с первой тренировки',
    colorToken: 'text-white',
    fontWeight: 'extrabold',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'hero.subtitle',
    label: 'Hero — подзаголовок',
    type: 'short',
    text: 'Научные формулы для силы, восстановления и защиты суставов. Без лактозы. Без компромиссов.',
    colorToken: 'text-slate-300',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'hero.cta.primary',
    label: 'Hero — CTA основная',
    type: 'short',
    text: 'Выбрать продукт',
    colorToken: 'text-white',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'hero.cta.secondary',
    label: 'Hero — CTA вторичная',
    type: 'short',
    text: 'Читать отзывы',
    colorToken: 'text-slate-100',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'hero.featured',
    label: 'Hero — подпись к featured продукту',
    type: 'short',
    text: 'Hydro Protein - флагман линейки',
    colorToken: 'text-slate-100',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'hero.featuredProductId',
    label: 'Hero — ID товара для карточки справа',
    type: 'short',
    text: '',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'about.title',
    label: 'Главная — О нас заголовок',
    type: 'short',
    text: 'О нас',
    colorToken: 'text-slate-900',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'hits.title',
    label: 'Хиты — заголовок',
    type: 'short',
    text: 'Хиты продаж',
    colorToken: 'text-slate-100',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'reviews.title',
    label: 'Отзывы — заголовок',
    type: 'short',
    text: 'Отзывы спортсменов',
    colorToken: 'text-slate-900',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'markers.title',
    label: 'Маркеры доверия — заголовок',
    type: 'short',
    text: 'Доверительные маркеры',
    colorToken: 'text-slate-900',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'markers.item1',
    label: 'Маркеры доверия — пункт 1',
    type: 'short',
    text: 'GMP и HACCP стандарты',
    colorToken: 'text-slate-700',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'markers.item2',
    label: 'Маркеры доверия — пункт 2',
    type: 'short',
    text: 'Прозрачный состав',
    colorToken: 'text-slate-700',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'markers.item3',
    label: 'Маркеры доверия — пункт 3',
    type: 'short',
    text: 'Регулярные обзоры',
    colorToken: 'text-slate-700',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'lineup.title',
    label: 'Линейка — заголовок',
    type: 'short',
    text: 'Вся линейка',
    colorToken: 'text-slate-100',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'reviewsCta.title',
    label: 'Отзывы CTA — заголовок',
    type: 'short',
    text: 'Реальные отзывы о Sprint Power',
    colorToken: 'text-white',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'reviewsCta.text',
    label: 'Отзывы CTA — текст',
    type: 'short',
    text: 'На странице отзывов можно посмотреть все отзывы и сразу оставить свой после покупки.',
    colorToken: 'text-slate-300',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'reviewsCta.buttonLabel',
    label: 'Отзывы CTA — кнопка',
    type: 'short',
    text: 'Перейти к отзывам',
    colorToken: 'text-white',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'reviewsCta.href',
    label: 'Отзывы CTA — ссылка',
    type: 'short',
    text: '/otzyvy',
    colorToken: 'text-slate-100',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'crossBrand.title',
    label: 'Кросс-бренд — заголовок',
    type: 'short',
    text: 'Inner Health',
    colorToken: 'text-slate-900',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'crossBrand.text',
    label: 'Кросс-бренд — текст',
    type: 'short',
    text: 'Inner Health поддерживает здоровье, красоту и молодость, активное долголетие. В ассортименте — инновационные формы пептидного коллагена и суперфуды из грибов: ежовик гребенчатый, рейши, кордицепс, лисичка, траметес и другие виды — с дозировками и схемами приёма, опирающимися на исследования и практику превентивной медицины.',
    colorToken: 'text-slate-600',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'crossBrand.cta',
    label: 'Кросс-бренд — CTA',
    type: 'short',
    text: 'Перейти на сайт',
    colorToken: 'text-white',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'faq.title',
    label: 'FAQ — заголовок',
    type: 'short',
    text: 'Частые вопросы',
    colorToken: 'text-slate-900',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'faq.item1',
    label: 'FAQ — вопрос 1',
    type: 'short',
    text: 'Как выбрать продукт под цель?',
    colorToken: 'text-slate-800',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'faq.item2',
    label: 'FAQ — вопрос 2',
    type: 'short',
    text: 'Можно ли сочетать протеин и коллаген?',
    colorToken: 'text-slate-800',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'faq.item3',
    label: 'FAQ — вопрос 3',
    type: 'short',
    text: 'Сколько протеина нужно в день?',
    colorToken: 'text-slate-800',
  },
  {
    brand: 'sprint-power',
    page: 'home',
    key: 'faq.cta',
    label: 'FAQ — CTA',
    type: 'short',
    text: 'Посмотреть ответы на все частозадаваемые вопросы',
    colorToken: 'text-white',
  },

  // About page — Sprint Power
  {
    brand: 'sprint-power',
    page: 'about',
    key: 'about.block1',
    label: 'О нас — блок 1 (формула красоты)',
    type: 'rich',
    richJson: {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Формула красоты и молодости существует. Главное в ней не дорогие крема, сыворотки, кондиционеры и шампуни. Красота рождается изнутри. Здоровые люди обворожительны по-особому.',
            },
          ],
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Sprint Power – это инновационные здоровьесберегающие продукты с нутрикосметическим эффектом. Они расширяют границы вашего потенциала. С ними ваш белковый статус в норме. А ухоженная, упругая кожа, густые, блестящие волосы, легкая походка, стройное тело вне времени, вне возраста.',
            },
          ],
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Все от разработки формул и производства основного сырья делаем в России. Стоимость продукции не обременена затратами на логистику и колебаниями курса доллара.',
            },
          ],
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Чистые составы без дополнительных объемных реагентов, консервантов, красителей, подсластителей. Высокая биодоступность и эффективная синергия компонентов. Результативность пролонгирована. Ее чувствуют, видят, ценят.',
            },
          ],
        },
      ],
    } as JSONContent,
  },
  {
    brand: 'sprint-power',
    page: 'about',
    key: 'about.block2.title',
    label: 'О нас — блок 2 заголовок',
    type: 'short',
    text: 'Sprint Power',
  },
  {
    brand: 'sprint-power',
    page: 'about',
    key: 'about.block2.text',
    label: 'О нас — блок 2 текст',
    type: 'rich',
    richJson: {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Sprint Power на рынке с 2022 года, но уже сыскала доверие покупателей. Более 5000 человек каждый день становятся с нами здоровее и возвращаются вновь и вновь. Особая гордость – более 2000 положительных отзывов, которые вдохновляют нас идти дальше. Бесценно доверие врачей конвенциальной и превентивной медицины, нутрициологов, диетологов, косметологов.',
            },
          ],
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Сотрудничаем с Международным институтом PreventAge, Университетом образовательной медицины (UOM), Международным институтом интегративной нутрициологии (МИИН), Первым Московским государственным медицинским университетом им. И.М. Сеченова.',
            },
          ],
        },
      ],
    } as JSONContent,
  },

  // About page
  {
    page: 'about',
    key: 'about.block1',
    label: 'О нас — блок 1 (формула красоты)',
    type: 'rich',
    richJson: {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Формула красоты и молодости существует. Главное в ней не дорогие крема, сыворотки, кондиционеры и шампуни. Красота рождается изнутри. Здоровые люди обворожительны по-особому.',
            },
          ],
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Inner Health – это инновационные здоровьесберегающие продукты с нутрикосметическим эффектом. Они расширяют границы вашего потенциала. С ними ваш белковый статус в норме. А ухоженная, упругая кожа, густые, блестящие волосы, легкая походка, стройное тело вне времени, вне возраста.',
            },
          ],
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Все от разработки формул и производства основного сырья делаем в России. Стоимость продукции не обременена затратами на логистику и колебаниями курса доллара.',
            },
          ],
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Чистые составы без дополнительных объемных реагентов, консервантов, красителей, подсластителей. Высокая биодоступность и эффективная синергия компонентов. Результативность пролонгирована. Ее чувствуют, видят, ценят.',
            },
          ],
        },
      ],
    } as JSONContent,
  },
  {
    page: 'about',
    key: 'about.block2.title',
    label: 'О нас — блок 2 заголовок',
    type: 'short',
    text: 'Inner Health',
  },
  {
    page: 'about',
    key: 'about.block2.text',
    label: 'О нас — блок 2 текст',
    type: 'rich',
    richJson: {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Inner Health на рынке с 2022 года, но уже сыскала доверие покупателей. Более 5000 человек каждый день становятся с нами здоровее и возвращаются вновь и вновь. Особая гордость – более 2000 положительных отзывов, которые вдохновляют нас идти дальше. Бесценно доверие врачей конвенциальной и превентивной медицины, нутрициологов, диетологов, косметологов.',
            },
          ],
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Сотрудничаем с Международным институтом PreventAge, Университетом образовательной медицины (UOM), Международным институтом интегративной нутрициологии (МИИН), Первым Московским государственным медицинским университетом им. И.М. Сеченова.',
            },
          ],
        },
      ],
    } as JSONContent,
  },

  // About images
  {
    page: 'about',
    key: 'about.image1.src',
    label: 'О нас — изображение 1 (URL)',
    type: 'short',
    text: '/images/o-nas/face-lift.jpg',
  },
  {
    page: 'about',
    key: 'about.image1.alt',
    label: 'О нас — изображение 1 alt',
    type: 'short',
    text: 'Красота и здоровье изнутри',
  },
  {
    page: 'about',
    key: 'about.image2.src',
    label: 'О нас — изображение 2 (URL)',
    type: 'short',
    text: '/images/o-nas/nutrition.jpg',
  },
  {
    page: 'about',
    key: 'about.image2.alt',
    label: 'О нас — изображение 2 alt',
    type: 'short',
    text: 'Питание и здоровый образ жизни',
  },

  // Каталог — шрифт названий категорий (главная + страница каталога)
  {
    page: 'catalog',
    key: 'categories.fontVariant',
    label: 'Шрифт названий категорий',
    type: 'short',
    text: 'display',
  },

  // Контакты
  {
    page: 'contacts',
    key: 'contacts.title',
    label: 'Контакты — заголовок страницы',
    type: 'short',
    text: 'Контакты',
  },
  {
    page: 'contacts',
    key: 'contacts.section.contacts_title',
    label: 'Контакты — заголовок секции контактов',
    type: 'short',
    text: 'Контакты',
  },
  {
    page: 'contacts',
    key: 'contacts.label.phone',
    label: 'Контакты — подпись телефона',
    type: 'short',
    text: 'Телефон:',
  },
  {
    page: 'contacts',
    key: 'contacts.label.email',
    label: 'Контакты — подпись email',
    type: 'short',
    text: 'Электронная почта:',
  },
  {
    page: 'contacts',
    key: 'contacts.section.showroom_title',
    label: 'Контакты — заголовок секции шоурума',
    type: 'short',
    text: 'Наш шоурум находится по адресу:',
  },
  {
    page: 'contacts',
    key: 'contacts.section.schedule_title',
    label: 'Контакты — заголовок режима работы',
    type: 'short',
    text: 'Режим работы:',
  },
  {
    page: 'contacts',
    key: 'contacts.section.write_title',
    label: 'Контакты — заголовок блока связи',
    type: 'short',
    text: 'Написать или позвонить:',
  },
  {
    page: 'contacts',
    key: 'contacts.phone',
    label: 'Контакты — телефон',
    type: 'short',
    text: '+7 (989) 103-91-92',
  },
  {
    page: 'contacts',
    key: 'contacts.email',
    label: 'Контакты — email',
    type: 'short',
    text: 'innerhealth@mail.ru',
  },
  {
    page: 'contacts',
    key: 'contacts.address',
    label: 'Контакты — адрес шоурума',
    type: 'short',
    text: 'г. Москва, набережная Новикова-Прибоя, 6 к4, 2-й этаж, офис Inner Health',
  },
  {
    page: 'contacts',
    key: 'contacts.working_weekdays',
    label: 'Контакты — режим будни',
    type: 'short',
    text: 'Будние дни: с 10 до 22',
  },
  {
    page: 'contacts',
    key: 'contacts.working_weekends',
    label: 'Контакты — режим выходные',
    type: 'short',
    text: 'Выходные: с 12 до 18',
  },
  {
    page: 'contacts',
    key: 'contacts.working_note',
    label: 'Контакты — примечание к режиму',
    type: 'short',
    text: '*по предварительному звонку',
  },

  // Корзина
  {
    page: 'cart',
    key: 'cart.paymentSuccessMessage',
    label: 'Корзина — сообщение после успешной оплаты',
    type: 'rich',
    richJson: {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Вы успешно оплатили заказ, информация о составе и доставке придет на указанную почту.',
            },
          ],
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Если письмо не доставлено, проверьте спам и напишите сразу нам.',
            },
          ],
        },
        {
          type: 'paragraph',
          content: [
            {
              type: 'text',
              text: 'Для подключения уведомлений в мессенджерах MAX или Telegram требуется ',
            },
            {
              type: 'text',
              text: 'регистрация',
              marks: [
                {
                  type: 'link',
                  attrs: {
                    href: '/register',
                  },
                },
              ],
            },
            {
              type: 'text',
              text: '.',
            },
          ],
        },
      ],
    } as JSONContent,
  },

  // Сертификаты соответствия
  {
    page: 'certificates',
    key: 'certificates.title',
    label: 'Сертификаты — заголовок страницы',
    type: 'short',
    text: 'Сертификаты соответствия',
  },
  {
    page: 'certificates',
    key: 'certificates.subtitle',
    label: 'Сертификаты — подзаголовок страницы',
    type: 'short',
    text: 'Документы, подтверждающие качество и соответствие продукции требованиям безопасности',
    colorToken: 'text-slate-500',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image1.src',
    label: 'Сертификаты — галерея (изображение 1 URL)',
    type: 'short',
    text: '/images/gallery/gallery-1.png',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image1.alt',
    label: 'Сертификаты — галерея (изображение 1 alt)',
    type: 'short',
    text: 'Сертификат 1',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image2.src',
    label: 'Сертификаты — галерея (изображение 2 URL)',
    type: 'short',
    text: '/images/gallery/gallery-2.png',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image2.alt',
    label: 'Сертификаты — галерея (изображение 2 alt)',
    type: 'short',
    text: 'Сертификат 2',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image3.src',
    label: 'Сертификаты — галерея (изображение 3 URL)',
    type: 'short',
    text: '/images/gallery/gallery-3.png',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image3.alt',
    label: 'Сертификаты — галерея (изображение 3 alt)',
    type: 'short',
    text: 'Сертификат 3',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image4.src',
    label: 'Сертификаты — галерея (изображение 4 URL)',
    type: 'short',
    text: '',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image4.alt',
    label: 'Сертификаты — галерея (изображение 4 alt)',
    type: 'short',
    text: 'Сертификат 4',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image5.src',
    label: 'Сертификаты — галерея (изображение 5 URL)',
    type: 'short',
    text: '',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image5.alt',
    label: 'Сертификаты — галерея (изображение 5 alt)',
    type: 'short',
    text: 'Сертификат 5',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image6.src',
    label: 'Сертификаты — галерея (изображение 6 URL)',
    type: 'short',
    text: '',
  },
  {
    page: 'certificates',
    key: 'certificates.gallery.image6.alt',
    label: 'Сертификаты — галерея (изображение 6 alt)',
    type: 'short',
    text: 'Сертификат 6',
  },
  {
    page: 'certificates',
    key: 'certificates.section.about.title',
    label: 'Сертификаты — секция “О документах” заголовок',
    type: 'short',
    text: 'О документах',
  },
  {
    page: 'certificates',
    key: 'certificates.section.about.p1',
    label: 'Сертификаты — секция “О документах” абзац 1',
    type: 'short',
    text: 'Inner Health уделяет особое внимание качеству и безопасности продукции. Ниже представлены сертификаты соответствия, декларации о соответствии и иные документы, подтверждающие соответствие товаров действующим нормам и стандартам.',
  },
  {
    page: 'certificates',
    key: 'certificates.section.about.p2',
    label: 'Сертификаты — секция “О документах” абзац 2',
    type: 'short',
    text: 'При необходимости вы можете запросить копии документов по электронной почте:',
  },
  {
    page: 'certificates',
    key: 'certificates.section.declarations.title',
    label: 'Сертификаты — секция “Декларации” заголовок',
    type: 'short',
    text: 'Декларации о соответствии ТР ТС',
  },
  {
    page: 'certificates',
    key: 'certificates.section.declarations.p1',
    label: 'Сертификаты — секция “Декларации” абзац',
    type: 'short',
    text: 'Продукция, реализуемая в рамках Таможенного союза (ЕАЭС), сопровождается декларациями о соответствии техническим регламентам ТР ТС (например, ТР ТС 021/2011 «О безопасности пищевой продукции», ТР ТС 029/2012 и др.), где применимо.',
  },
  {
    page: 'certificates',
    key: 'certificates.section.declarations.note',
    label: 'Сертификаты — секция “Декларации” примечание',
    type: 'short',
    text: 'Декларации хранятся у продавца и предоставляются по запросу покупателя или контролирующих органов.',
    colorToken: 'text-slate-600',
  },
  {
    page: 'certificates',
    key: 'certificates.section.productCertificates.title',
    label: 'Сертификаты — секция “Сертификаты на продукцию” заголовок',
    type: 'short',
    text: 'Сертификаты на продукцию',
  },
  {
    page: 'certificates',
    key: 'certificates.section.productCertificates.p1',
    label: 'Сертификаты — секция “Сертификаты на продукцию” абзац',
    type: 'short',
    text: 'Отдельные категории товаров могут иметь добровольную сертификацию или сертификаты соответствия по российским и международным стандартам (в том числе органическая продукция, при наличии).',
  },
  {
    page: 'certificates',
    key: 'certificates.section.productCertificates.note',
    label: 'Сертификаты — секция “Сертификаты на продукцию” примечание',
    type: 'short',
    text: 'Актуальный перечень сертификатов и сканы документов будут размещены в этом разделе. По вопросам наличия сертификатов на конкретный товар обращайтесь в службу поддержки.',
    colorToken: 'text-slate-600',
  },
  {
    page: 'certificates',
    key: 'certificates.section.contacts.title',
    label: 'Сертификаты — секция “Контакты” заголовок',
    type: 'short',
    text: 'Контакты',
  },
  {
    page: 'certificates',
    key: 'certificates.section.contacts.intro',
    label: 'Сертификаты — секция “Контакты” вступление',
    type: 'short',
    text: 'По вопросам сертификатов и документов:',
  },
  {
    page: 'certificates',
    key: 'certificates.section.contacts.email',
    label: 'Сертификаты — email для запросов',
    type: 'short',
    text: 'innerhealth@mail.ru',
  },
  {
    page: 'certificates',
    key: 'certificates.section.contacts.contactsPageLabel',
    label: 'Сертификаты — текст ссылки на страницу контактов',
    type: 'short',
    text: 'Контакты',
  },

  // FAQ
  {
    page: 'faq',
    key: 'faq.title',
    label: 'FAQ — заголовок страницы',
    type: 'short',
    text: 'Часто задаваемые вопросы',
  },
  {
    page: 'faq',
    key: 'faq.subtitle',
    label: 'FAQ — подзаголовок страницы',
    type: 'short',
    text: 'Ответы на популярные вопросы о товарах, доставке и оформлении заказа.',
  },
  {
    brand: 'sprint-power',
    page: 'faq',
    key: 'faq.subtitle',
    label: 'FAQ — подзаголовок страницы',
    type: 'short',
    text: 'Ответы на частые вопросы о линейке Sprint Power, приеме продуктов, доставке и заказах.',
  },
  {
    brand: 'sprint-power',
    page: 'faq',
    key: 'faq.q1',
    label: 'FAQ — вопрос 1',
    type: 'short',
    text: 'Как выбрать продукт Sprint Power под цель тренировки?',
  },
  {
    brand: 'sprint-power',
    page: 'faq',
    key: 'faq.a1',
    label: 'FAQ — ответ 1',
    type: 'short',
    text: 'Для набора и восстановления выбирайте белковые комплексы, для выносливости — формулы поддержки энергии и электролитов. Начните с базового продукта и отслеживайте самочувствие 2-3 недели.',
  },
  {
    brand: 'sprint-power',
    page: 'faq',
    key: 'faq.q2',
    label: 'FAQ — вопрос 2',
    type: 'short',
    text: 'Можно ли сочетать несколько продуктов Sprint Power одновременно?',
  },
  {
    brand: 'sprint-power',
    page: 'faq',
    key: 'faq.a2',
    label: 'FAQ — ответ 2',
    type: 'short',
    text: 'Да, но лучше вводить их поэтапно. Начните с одного продукта, затем добавляйте следующий с интервалом 5-7 дней, чтобы оценить переносимость и эффект.',
  },
  {
    brand: 'sprint-power',
    page: 'faq',
    key: 'faq.q3',
    label: 'FAQ — вопрос 3',
    type: 'short',
    text: 'Когда принимать продукты: до или после тренировки?',
  },
  {
    brand: 'sprint-power',
    page: 'faq',
    key: 'faq.a3',
    label: 'FAQ — ответ 3',
    type: 'short',
    text: 'Зависит от формулы: продукты для энергии обычно принимают до тренировки, для восстановления — после. Ориентируйтесь на рекомендации на странице товара.',
  },
  {
    brand: 'sprint-power',
    page: 'faq',
    key: 'faq.q4',
    label: 'FAQ — вопрос 4',
    type: 'short',
    text: 'Есть ли доставка по России и как быстро приходит заказ?',
  },
  {
    brand: 'sprint-power',
    page: 'faq',
    key: 'faq.a4',
    label: 'FAQ — ответ 4',
    type: 'short',
    text: 'Да, доставляем по России через СДЭК. Срок зависит от региона и обычно отображается при оформлении заказа.',
  },

  // Сотрудничество
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.title',
    label: 'Сотрудничество — заголовок страницы',
    type: 'short',
    text: 'Сотрудничество',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.subtitle',
    label: 'Сотрудничество — подзаголовок страницы',
    type: 'short',
    text: 'Inner Health: внешние трансформации через красоту изнутри',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.form.title',
    label: 'Сотрудничество — заголовок блока формы',
    type: 'short',
    text: 'Оставить заявку',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.form.subtitle',
    label: 'Сотрудничество — подпись блока формы',
    type: 'short',
    text: 'Заполните форму — мы свяжемся с вами и обсудим условия сотрудничества.',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.intro.title',
    label: 'Сотрудничество — секция вступления (заголовок)',
    type: 'short',
    text: 'Вступайте в команду Inner Health!',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.intro.p1',
    label: 'Сотрудничество — секция вступления (абзац 1)',
    type: 'short',
    text: 'Объединяем тех, кто точно знает, что молодость и красота – физическое проявление внутреннего здоровья.',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.intro.p2',
    label: 'Сотрудничество — секция вступления (абзац 2)',
    type: 'short',
    text: 'В основе разработок наших препаратов — знание физиологии, научные исследования, превентивная практика, передовые технологии и контроль качества.',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.intro.p3',
    label: 'Сотрудничество — секция вступления (абзац 3, акцент)',
    type: 'short',
    text: 'Эффективные формулы. Максимальная биодоступность. Бескомпромиссный результат. Пролонгированное действие.',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.audience.title',
    label: 'Сотрудничество — секция “С кем работаем” (заголовок)',
    type: 'short',
    text: 'С кем мы работаем',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.audience.text',
    label: 'Сотрудничество — секция “С кем работаем” (текст)',
    type: 'short',
    text: 'Сотрудничаем с врачами, нутрициологами, health-coach, специалистами помогающих профессий, фитнес-тренерами, косметологами.',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.benefits.title',
    label: 'Сотрудничество — секция “Вы получите” (заголовок)',
    type: 'short',
    text: 'Вы получите',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.benefits.item1',
    label: 'Сотрудничество — секция “Вы получите” (пункт 1)',
    type: 'short',
    text: 'Скидка до 25% по личному промокоду для вас, ваших клиентов, пациентов, друзей и знакомых.',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.benefits.item2',
    label: 'Сотрудничество — секция “Вы получите” (пункт 2)',
    type: 'short',
    text: 'Ежемесячный кешбэк от суммы заказа по промокоду — выплачивается по результатам месяца на вашу банковскую карту.',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.benefits.item3',
    label: 'Сотрудничество — секция “Вы получите” (пункт 3)',
    type: 'short',
    text: 'Выгодные условия для оптовых закупок и работы представительств в регионах.',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.extra.title',
    label: 'Сотрудничество — секция “А также” (заголовок)',
    type: 'short',
    text: 'А также',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.extra.item1',
    label: 'Сотрудничество — секция “А также” (пункт 1)',
    type: 'short',
    text: 'Есть интересные кейсы применения наших продуктов и вы готовы ими делиться — предоставим свои информационные ресурсы.',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.extra.item2',
    label: 'Сотрудничество — секция “А также” (пункт 2)',
    type: 'short',
    text: 'Интересно апробировать в профилактических и терапевтических протоколах и есть возможность фиксировать результат — обсудим и предоставим особые условия на приобретение продукции.',
  },
  {
    page: 'sotrudnichestvo',
    key: 'cooperation.extra.item3',
    label: 'Сотрудничество — секция “А также” (пункт 3)',
    type: 'short',
    text: 'Изучаете рынок продуктов для здоровья и делаете обзоры в соцсетях — расскажем о преимуществах и предоставим продукты на тестирование.',
  },

  // Footer — юридический блок
  {
    page: 'footer',
    key: 'footer.legal.fullName',
    label: 'Футер — полное наименование',
    type: 'short',
    text: 'ИП Кудимов Валерий Валерьевич',
  },
  {
    page: 'footer',
    key: 'footer.legal.address',
    label: 'Футер — юридический адрес',
    type: 'short',
    text: '196140, г. Санкт-Петербург, Пулковское шоссе, д. 73, корп. 2, стр. 1, кв. 85',
  },
  {
    page: 'footer',
    key: 'footer.bank.correspondentAccount',
    label: 'Футер — корреспондентский счёт',
    type: 'short',
    text: '30101 810 4 0000 0000225',
  },
  {
    page: 'footer',
    key: 'footer.bank.bic',
    label: 'Футер — БИК',
    type: 'short',
    text: '044525225',
  },
  {
    page: 'footer',
    key: 'footer.bank.ogrnip',
    label: 'Футер — ОГРНИП',
    type: 'short',
    text: '322784700221371',
  },
  {
    page: 'footer',
    key: 'footer.bank.inn',
    label: 'Футер — ИНН',
    type: 'short',
    text: '550622300904',
  },
  // Home — "Как заказать"
  {
    page: 'home',
    key: 'howToOrder.title',
    label: 'Как заказать — заголовок',
    type: 'short',
    text: 'Как заказать',
  },
  {
    page: 'home',
    key: 'howToOrder.step1.title',
    label: 'Как заказать — шаг 1 заголовок',
    type: 'short',
    text: 'Выберите товары',
  },
  {
    page: 'home',
    key: 'howToOrder.step1.text',
    label: 'Как заказать — шаг 1 текст',
    type: 'short',
    text: 'Добавьте позиции в корзину из каталога или оформите «в 1 клик» на карточке товара.',
  },
  {
    page: 'home',
    key: 'howToOrder.step1.href',
    label: 'Как заказать — шаг 1 ссылка (href)',
    type: 'short',
    text: '/catalog',
  },
  {
    page: 'home',
    key: 'howToOrder.step1.linkLabel',
    label: 'Как заказать — шаг 1 текст ссылки',
    type: 'short',
    text: 'В каталог',
  },
  {
    page: 'home',
    key: 'howToOrder.step2.title',
    label: 'Как заказать — шаг 2 заголовок',
    type: 'short',
    text: 'Оформите заказ',
  },
  {
    page: 'home',
    key: 'howToOrder.step2.text',
    label: 'Как заказать — шаг 2 текст',
    type: 'short',
    text: 'Укажите контакты, способ доставки СДЭК (ПВЗ или курьер) и оплату через ЮKassa.',
  },
  {
    page: 'home',
    key: 'howToOrder.step2.href',
    label: 'Как заказать — шаг 2 ссылка (href)',
    type: 'short',
    text: '/faq',
  },
  {
    page: 'home',
    key: 'howToOrder.step2.linkLabel',
    label: 'Как заказать — шаг 2 текст ссылки',
    type: 'short',
    text: 'Вопросы о доставке',
  },
  {
    page: 'home',
    key: 'howToOrder.step3.title',
    label: 'Как заказать — шаг 3 заголовок',
    type: 'short',
    text: 'Получите и пользуйтесь',
  },
  {
    page: 'home',
    key: 'howToOrder.step3.text',
    label: 'Как заказать — шаг 3 текст',
    type: 'short',
    text: 'Отслеживайте отправление, при необходимости свяжитесь с нами через раздел контактов.',
  },
  {
    page: 'home',
    key: 'howToOrder.step3.href',
    label: 'Как заказать — шаг 3 ссылка (href)',
    type: 'short',
    text: '/contacts',
  },
  {
    page: 'home',
    key: 'howToOrder.step3.linkLabel',
    label: 'Как заказать — шаг 3 текст ссылки',
    type: 'short',
    text: 'Контакты',
  },
  {
    page: 'legal-privacy',
    key: 'legal-privacy.body',
    label: 'Политика конфиденциальности — основной текст',
    type: 'rich',
    richJson: { type: 'doc', content: [] },
  },
  {
    page: 'legal-oferta',
    key: 'legal-oferta.body',
    label: 'Публичная оферта — основной текст',
    type: 'rich',
    richJson: { type: 'doc', content: [] },
  },
]
